# Updated as of 6/11/2024
# Testing the thresholding package from Carissa's instructions
# https://github.com/carissableker/thresholding?tab=readme-ov-file#example

# file name prefixes for future reference 
# it_suffix <- ".iterative.txt"
# stat_suffix <- ".statistical_errors.txt"
# local_global <- ".local_global.txt"

# Installing the package (for development)
install.packages("../thresholding_1.0.0.tar.gz", type='source', repos=NULL)

# Load and attach the thresholding namespace 
library(thresholding)

# Relative path to .ncol data file
data_file <- './example/HumanCellCycleSubset.ncol'
data_prefix <- './example/HumanCellCycleSubset'   # prefix used in other functions in package


#          Step 1 - make edge weight histogram of data
# First we can take a look at the edge weight distribution
# Use '?thresholding::edge_hist' in R terminal for more documentation
bin_width <- 0.01
weight_hist <- edge_hist(data_file, bin_width = bin_width)
show(weight_hist)

#          Step 2 - running analysis on the graph
# Now let's do the analysis of our graph. 
# To make it time efficient, lets do percolation, significance and power, and scale-free methods. 
# By default it will also calculate density at each threshold. 
# We'll start at a lower threshold limit of 0.6, and leave the increment at the default of 0.01. 
# Remember to give the number of samples using -n.
# 
# Method integers given for reference here:
#       0 - all
#       1 - significance and power calculations (only valid for Pearson CC)
#       2 - local-global
#       3 - scale free
#       4 - maximal cliques
#       5 - spectral methods
#       6 - random matrix theory
#       7 - clustering coefficient
#       8 - percolation
#       Use '?anaylsis' for more documentation

# NOTE: num_samples, or number of samples, is NEEDED for doing method 1 (significance and power 
# calculations). Supplying num_samples <= 4  when using method 1 will cause the analysis()
# function to end execution. Not supplying the proper number of samples will lead to incorrect analysis()
# results. There were 13 samples used in the data file given from Carissa's example data file
# (HumanCellCycleSubset.ncol)
methods <- c(8, 1, 3)    # select the three desired analysis methods
starting_thresh <- 0.6   # choose lower bound thresholding value the thresholding loop begins at
num_samples <- 13 

thresholding::analysis(data_file, 
                       methods = methods,
                       lower = starting_thresh,
                       num_samples = num_samples,
                      )


# Just doing spectral thresholding 
# analysis(data_file, 
#          methods = 5,
#          lower = starting_thresh
#          )


#it_fname <- "./example/HumanCellCycleSubset-138.iterative.txt"
#stat_fname <- "./example/HumanCellCycleSubset-138.statistical_errors.txt"

#          Step 3 - Get analysis results
# Use get_results to see the output of the thresholding analysis across different runs
# of the same data file
# Data prefix is the same prefix used as the parameter to analysis which was 
#   A.) user provided
#   B.) automatically generated by analysis function
#       in which case, use the prefix given from the standard output in the R terminal
#       for the proper prefix to use
# output_prefix <- "./example/HumanCellCycleSubset"

output_prefix <- "./example/HumanCellCycleSubset"
get_results_out <- get_results(data_prefix)
get_res_D <- get_results_out$D
get_res_alpha <- get_res_D$alpha

# Logical change - make get_results check which methods were used 
# and only save those to D for output (no NaN'ers for things not used)
print(get_results_out$D)
print(get_res_D$whole_graph)
print(get_res_D$alpha)

#         Step 4a/b - Observe graph method thresholds and threshold graph
# Testing the plot functionalites
# can also do this to just display the plot instead of return it
# get_results(data_prefix, plot_iterative = TRUE)
# THIS API  SHOULD NO LONGER WORK!!!
# iter_only <- get_iter_t_vals(data_prefix)
# plot_t_vs_ev(iter_only$Iter_df, get_res_D)
iter_infile <- "./example/HumanCellCycleSubset"
thresholding::plot_t_vs_ev(iter_infile)
# Thresholding the graph and saving to a new output file
threshold <- 0.79
abs_outfile <- "./example/HumanCellCycleSubset-ABSTHOLD.ncol"

# User option - allow option for copying output file if there 
#         another file with a modified name (thresh suffix) to distinguish
#         use a

# Add note if when "No" ends to let user know what happens
absolute_threshold(data_file,
                   abs_outfile,
                   threshold)
# Minor work to be done here to get things working
#threshold(data_file, abs_outfile, ...)