# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Manually exported in NAMESPACE
function_test <- function(c) {
    .Call('_thresholding_function_test', PACKAGE = 'thresholding', c)
}

#' Prints out 10 numbers
#' @param i - an integer that gets printed right back out
#' Manually exported in NAMESPACE
print_vector <- function(i) {
    invisible(.Call('_thresholding_print_vector', PACKAGE = 'thresholding', i))
}

#' Display argument information on terminal for thresholding::thresholdAnalysis()
#' 
help <- function() {
    invisible(.Call('_thresholding_help', PACKAGE = 'thresholding'))
}

#' Main graph thresholding analysis function
#' @param infile: Name of .ncol graph file to read in for analysis
#' @param outfile_prefix: Prefix of output file in which analysis will be redirected to (Ex: <PREFIX>.iterative.txt )
#' @param methods: Comma separated list of analysis methods, listed if thresholding::help() is called (defaults to none)
thresholdAnalysis <- function(infile, outfile_prefix, methods = "", lower = 0.5, upper = 0.99, increment = 0.01, window_size = 5L, min_partition_size = 10L, min_clique_size = 5L, min_alpha = 0, max_alpha = 4, alpha_increment = 0.1, num_samples = 0L, significance_alpha = 0.01, bonferroni_corrected = 0L) {
    invisible(.Call('_thresholding_thresholdAnalysis', PACKAGE = 'thresholding', infile, outfile_prefix, methods, lower, upper, increment, window_size, min_partition_size, min_clique_size, min_alpha, max_alpha, alpha_increment, num_samples, significance_alpha, bonferroni_corrected))
}

rcpp_hello_world <- function() {
    .Call('_thresholding_rcpp_hello_world', PACKAGE = 'thresholding')
}

