# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Analysis methods for absolute thresholding of weighted graphs
#' 
#' Weighted graphs thresholding analysis. This function iteratively performs absolute thresholding the input graph at specified threshold values [\code{lower}, \code{upper}].
#' The function's methods parameter controls which graph analysis methods are performed at each threshold value.
#' Execution of \code{analysis()} ends after the '\code{upper}' threshold is reached, or if the graph becomes
#' too small to threshold further.
#'  
#' The results at each step are written output files. There is always at least one output file, but there can be 
#' up to two depending on the methods passed:
#' \itemize{
#'   \item \code{<outfile_prefix>.iterative.txt}:          (\strong{guaranteed})
#'   \item \code{<outfile_prefix>.statistical_errors.txt}: (method \strong{2})
#' }
#' 
#' Refer to Dr. Carissa Bleker's dissertation for more information about these analysis methods: \url{https://trace.tennessee.edu/utk_graddiss/5894/}
#' 
#' @param infile string. File path for .ncol graph file (\url{https://lgl.sourceforge.net/}) to read in for analysis. 
#' This file must be space delimited for this function to properly read in the graph's information.
#' @param outfile_prefix string. Prefix of output file in which analysis will be redirected to. If this is not specified,
#'        \code{thresholding::analysis()} will auto generate the output file prefix to include the input file's 
#'        prefix and the method numbers (in ascending order)
#'          For example if the user requests methods \code{4} and \code{7} with an input file named \code{"myfile.tsv"} would be:
#'             \code{myfile-47.<method_name>.txt}. 
#'        The input file prefix will be determined by the characters preceding the first period ('.') character.
#'         Otherwise, the user-provided value for \code{outfile_prefix} and the method numbers (if any) will be used in the output file's name.
#' @param methods Numeric vector of analysis method integers. Defaults to an empty list (no analysis methods). These will be performed on each thresholding step and recorded
#' into the output file(s). The number to method translation is given below:  
#' \itemize{
#'   \item 1 = all
#'   \item 2 = significance and power calculations (only valid for Pearson CC)
#'   \item 3 = scale free
#'   \item 4 = maximal cliques
#'   \item 5 = spectral methods
#'   \item 6 = random matrix theory
#'   \item 7 = clustering coefficient
#'   \item 8 = percolation
#' }
#'  Refer to the following papers for more detailed description of these methods: 
#' \itemize{
#' \item Dr. Carissa Bleker's thresholding dissertation: \url{https://trace.tennessee.edu/utk_graddiss/5894/} 
#' \item Dr. Langston, Grady, and Bleker's thresholding paper: \url{https://web.eecs.utk.edu/~mlangsto/JCB-Thresholding-Paper.pdf}
#' }
#'         The method name in the outputfile name may vary based on the methods used. The name will either be \code{iterative} or \code{statistical_errors}.
#' @param lower numeric.Lower bound to begin thresholding loop at (default = 0.5 ; lower >= 0)
#' @param upper numeric. Hard upper bound that ends thresholding  loop when \code{lower} value is greater than \code{upper} value (Default = 0.99)
#' @param increment numeric. Size of increment step in the thresholding loop
#' @param window_size numeric. Sliding window size for spectral method (Default = 5)
#' @param min_partition_size integer. minimum size of graph or subgraph after threshold (Default = 10)
#' @param min_clique_size integer. Minimum size of maximal cliques in maximal clique count (Default = 5)
#' @param num_samples integer. Number of samples in Pearson Correlation Coefficient data (only used for \strong{analysis method 2 - Power and Significance calculations}).  
#'        \emph{\strong{\code{num_samples} must be positive, non-zero, and match the number of samples from the original dataset for method 2 to work.}} \emph{Not used in any other methods.}
#' @param significance_alpha numeric. Probability of rejecting the null hypothesis when the null hypothesis is true.  (Default = 0.01)
#' @param bonferroni_corrected boolean. Option to perform Bonferroni correction in \strong{method 2 - Significance and Power calculations}. 
#'        Applies Bonferroni correction to the value of significance_alpha if set to \code{TRUE}. \emph{Not used in any other methods.} (default \code{FALSE})
#' @param overwrite boolean. Determines whether output file with given or generated prefix will be overwritten. 
#'        Set this to \code{TRUE} to force overwrite the output file. The default, \code{FALSE}, will display a menu asking
#'        whether or not you wish to overwrite the output file. The examples are defaulted to \code{TRUE} to avoid prompting this menu if the 
#'        example output files already exist.
#' @examples
#' #######    Variable Set-Up     #######
#' library(thresholding)
#' data_file <- system.file('extdata', 'HumanCellCycleSubset.ncol', package = "thresholding")   
#' data_prefix <- './HumanCellCycleSubset-thresh-ex'  # prefix used for output file(s)
#' lower <- 0.6   
#'
#' #######    Example 1 - No methods #######
#' analysis(data_file, 
#'          outfile_prefix = data_prefix,
#'          lower = lower,
#'          overwrite = TRUE
#'          )
#'
#' #######    Example 2 - iterative and power/significance methods #######
#' data_file <- system.file('extdata', 'HumanCellCycleSubset.ncol', package = "thresholding") 
#' methods <- c(8, 2, 3)    # select the three desired analysis methods
#' lower <- 0.6             # choose lower bound thresholding value the thresholding loop begins at
#' num_samples <- 13        # ONLY FOR METHOD 2 - number of samples in data set
#' 
#' # Note: analysis() will autogenerate an output file name based 
#' #       on the input file path if a prefix is not passed.
#' analysis(data_file, 
#'          methods = methods,
#'          lower = lower,
#'          num_samples = num_samples,
#'          overwrite = TRUE
#'          )
#' \dontrun{
#' #######    Example 3 - More Iterative methods #######
#' # WARNING FOR EXAMPLES: this code may take a few minutes to run.
#' data_file <- system.file('extdata', 'HumanCellCycleSubset.ncol', package = "thresholding") 
#' methods <- c(3,4,5,6)
#' lower <- 0.7
#' 
#' # Note: By supplying an output file prefix, the only modification to the output
#' #       file will be "-###" where ### represents the analysis methods passed
#' #       to analysis(). This is done to distinguish between output files generated by analysis()
#' #       that have the same prefix, but potentially different methods.
#' analysis(data_file,
#'          outfile_prefix = "./example_2_it",
#'          methods = methods,
#'          lower = lower,
#'          overwrite = TRUE
#'         )
#'
#' }
#' @returns Nothing. \code{analysis()} writes all output to a file. The file path and file prefixes are printed on standard output when `analysis()` terminates.
analysis <- function(infile, outfile_prefix = "", methods = as.numeric( c()), lower = 0.5, upper = 0.99, increment = 0.01, window_size = 5L, min_partition_size = 10L, min_clique_size = 5L, num_samples = 0L, significance_alpha = 0.01, bonferroni_corrected = 0L, overwrite = FALSE) {
    invisible(.Call(`_thresholding_analysis`, infile, outfile_prefix, methods, lower, upper, increment, window_size, min_partition_size, min_clique_size, num_samples, significance_alpha, bonferroni_corrected, overwrite))
}

#' Strict thresholding for weighted graphs in \code{.ncol} format
#'
#' General graph thresholding function that reads in an \code{.ncol} graph file and writes
#' the thresholded graph to the file specified by \code{outfile}. The methods for thresholding
#' are presented in the comparative study paper linked here: \url{https://pubmed.ncbi.nlm.nih.gov/38781420/}
#' or in Carissa Bleker's dissertation: \url{https://trace.tennessee.edu/utk_graddiss/5894/}
#'
#' @param infile string. The input \code{.ncol} graph file to be thresholded.
#' @param outfile string. The path of the output file where the thresholded grpah will be written to.
#' @param method string. The method of thresholding can be one of these options:
#' \enumerate{
#'     \item \strong{\code{"absolute"}}: Retains all edges that are  greater than or equal to the 
#'            absolute value of the threshold value. (\code{weight} >= | \code{thresh} |)
#'     \item \strong{\code{"strict"}}: Retains edges that are strictly greater than \code{thresh} if
#'           \code{thresh} >= \code{0}.  If \code{thresh} < \code{0}, all negative edges less than
#'           \code{thresh} are retained.
#'     \item \strong{\code{"local-global"}}: Local the global pruning method mentioned in the thresholding papers
#'     \item \strong{\code{"rank"}}: Use the top ranked edges per vertex to threshold graph.
#'     }
#' @param thresh numeric. The value to threshold the graph. The affect of this value depends on the thresolding
#'        \code{method} used, which are described above. \strong{Only used in the \code{"strict"} and 
#'        \code{"absolute"} thresholding methods.}
#' @param local_global_alpha  numeric. Use local-global method to threshold with alpha = \code{local_global_alpha}. 
#'        \strong{Only used with \code{method == "local-global".}}
#' @param rank numeric. Use top \code{rank} ranked edges per vertex to threshold graph. \strong{Only used when
#'        \code{method} == "\code{rank}".}
#' @param overwrite boolean. A  parameter meant to prevent overwriting existing thresholded
#' graph files. The default (\code{FALSE}) will display a menu to the user if the passed
#' \code{outfile} already exists. Choosing \code{TRUE} will bypass this menu and overwrite
#' the existing file without interruption from a workflow.
#' @examples
#' # Load the package
#' library(thresholding)
#'
#' ################ Example 1 ###################
#' infile <- system.file('extdata', 'HumanCellCycleSubset.ncol', package = "thresholding")
#' thresholding::threshold(infile, 
#'                         outfile = "./HCCS-thresh-abs.ncol",
#'                         method = "absolute",
#'                         thresh = 0.8,
#'                         overwrite = TRUE
#'                         )
#' print("Check the path specified by 'outfile' to find the output containing the thresholded graph.")
#' \dontrun{
#' ################ Example 2 ###################
#' infile <- system.file('extdata', 'HumanCellCycleSubset.ncol', package = "thresholding") 
#' thresholding::threshold(infile, 
#'                         outfile = "./HCCS-thresh-strict.ncol",
#'                         method = "strict",
#'                         thresh = 0.8
#'                         )
#' ################ Example 3 ###################
#' infile <- system.file('extdata', 'HumanCellCycleSubset.ncol', package = "thresholding") 
#' thresholding::threshold(infile, 
#'                         outfile = "./HCCS-thresh-local-global.ncol",
#'                         method = "local-global",
#'                         local_global_alpha = 0.5
#'                         )
#' ################ Example 4 ###################
#' infile <- system.file('extdata', 'HumanCellCycleSubset.ncol', package = "thresholding") 
#' thresholding::threshold(infile, 
#'                         outfile = "./HCCS-thresh-strict.ncol",
#'                         method = "rank",
#'                         rank = 2
#'                         )
#' }
#' @returns Nothing. The thresholded graph is written to the file specified by outfile.
threshold <- function(infile, outfile, method = "absolute", thresh = 0.0, local_global_alpha = 0.0, rank = 0L, overwrite = FALSE) {
    .Call(`_thresholding_threshold`, infile, outfile, method, thresh, local_global_alpha, rank, overwrite)
}

