# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Display argument information on terminal for thresholding::analysis()
#' 
help <- function() {
    invisible(.Call(`_thresholding_help`))
}

#' Main graph thresholding analysis function
#' @param infile Name of .ncol graph file to read in for analysis
#' @param methods Comma separated list of analysis methods, listed if thresholding::help() is called (defaults to none)
#' @param outfile_prefix Prefix of output file in which analysis will be redirected to. This will be
#'          auto generated by thresholding::analysis() to include the input file's prefix and the ascending method numbers.
#'          The input file prefix will be determined by the characters preceding the first period ('.') character.
#'          An example if the user requests methods 4 and 7 with an input file named "myfile.tsv" would be:
#'             myfile-47.<method_name>.txt
#'         Method name can vary based on the methods used. This will either be iterative, local_global, or statistical_errors.
#' @param lower Lower bound to begin thresholding increment (lower >= 0)
#' @param upper Hard upper bound that ends thresholding loop when "lower" value is greater than "upper" value.
#' @param increment Size of increment step in the thresholding loop
#' @param window_size DOCUMENT THIS
#' @param min_partition_size DOCUMENT THIS
#' @param min_clique_size DOCUMENT THIS
#' @param min_alpha DOCUMENT THIS
#' @param max_alpha DOCUMENT THIS
#' @param alpha_increment DOCUMENT THIS
#' @param num_samples DOCUMENT THIS
#' @param significance_alpha DOCUMENT THIS
#' @param bonferroni_corrected DOCUMENT THIS
analysis <- function(infile, methods = as.numeric( c()), outfile_prefix = "", lower = 0.5, upper = 0.99, increment = 0.01, window_size = 5L, min_partition_size = 10L, min_clique_size = 5L, min_alpha = 0, max_alpha = 4, alpha_increment = 0.1, num_samples = 0L, significance_alpha = 0.01, bonferroni_corrected = 0L) {
    invisible(.Call(`_thresholding_analysis`, infile, methods, outfile_prefix, lower, upper, increment, window_size, min_partition_size, min_clique_size, min_alpha, max_alpha, alpha_increment, num_samples, significance_alpha, bonferroni_corrected))
}

